---
-- Schema for input data to be mapped to dwc-dp publishing model.
--

CREATE TABLE observations (
    "id" INTEGER,
    "uuid" VARCHAR(36),
    "observed_on_string" VARCHAR(39),
    "observed_on" VARCHAR(10),
    "time_observed_at" VARCHAR(23),
    "time_zone" VARCHAR(26),
    "user_id" INTEGER,
    "user_login" VARCHAR(15),
    "user_name" VARCHAR(21),
    "created_at" VARCHAR(23),
    "updated_at" VARCHAR(23),
    "quality_grade" VARCHAR(8),
    "license" VARCHAR(8),
    "url" VARCHAR(50),
    "image_url" VARCHAR(75),
    "sound_url" DOUBLE PRECISION,
    "tag_list" VARCHAR(56),
    "description" TEXT,
    "num_identification_agreements" INTEGER,
    "num_identification_disagreements" INTEGER,
    "captive_cultivated" BOOLEAN,
    "oauth_application_id" DOUBLE PRECISION,
    "place_guess" VARCHAR(78),
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "positional_accuracy" DOUBLE PRECISION,
    "private_place_guess" DOUBLE PRECISION,
    "private_latitude" DOUBLE PRECISION,
    "private_longitude" DOUBLE PRECISION,
    "public_positional_accuracy" DOUBLE PRECISION,
    "geoprivacy" VARCHAR(8),
    "taxon_geoprivacy" VARCHAR(8),
    "coordinates_obscured" BOOLEAN,
    "positioning_method" VARCHAR(3),
    "positioning_device" VARCHAR(6),
    "place_town_name" VARCHAR(16),
    "place_county_name" VARCHAR(11),
    "place_state_name" VARCHAR(10),
    "place_country_name" VARCHAR(13),
    "place_admin1_name" VARCHAR(10),
    "place_admin2_name" VARCHAR(11),
    "species_guess" VARCHAR(45),
    "scientific_name" VARCHAR(41),
    "common_name" VARCHAR(37),
    "iconic_taxon_name" VARCHAR(9),
    "taxon_id" INTEGER,
    "taxon_kingdom_name" VARCHAR(8),
    "taxon_phylum_name" VARCHAR(12),
    "taxon_subphylum_name" VARCHAR(12),
    "taxon_superclass_name" DOUBLE PRECISION,
    "taxon_class_name" VARCHAR(13),
    "taxon_subclass_name" VARCHAR(9),
    "taxon_superorder_name" DOUBLE PRECISION,
    "taxon_order_name" VARCHAR(14),
    "taxon_suborder_name" VARCHAR(15),
    "taxon_superfamily_name" VARCHAR(14),
    "taxon_family_name" VARCHAR(14),
    "taxon_subfamily_name" VARCHAR(20),
    "taxon_supertribe_name" VARCHAR(11),
    "taxon_tribe_name" VARCHAR(16),
    "taxon_subtribe_name" VARCHAR(17),
    "taxon_genus_name" VARCHAR(16),
    "taxon_genushybrid_name" DOUBLE PRECISION,
    "taxon_species_name" VARCHAR(29),
    "taxon_hybrid_name" DOUBLE PRECISION,
    "taxon_subspecies_name" VARCHAR(39),
    "taxon_variety_name" VARCHAR(41),
    "taxon_form_name" DOUBLE PRECISION,
    "field:plant or pollinator?" VARCHAR(10),
    "field:link key? required" TEXT,
    "field:associated observation" VARCHAR(153),
    "field:interaction->visited flower of" VARCHAR(33),
    "field:interaction->flower visited by" VARCHAR(35)
);
CREATE INDEX idx_occurrenceID ON observations(uuid);
