-- Before beginning, make the occurrenceStatus lowercase, consistent with the ENUM
-- values in the target database structure at 
-- https://github.com/gbif/model-dwc-dp/blob/master/gbif/dwc_dp_schema.sql

-- Fill the event table.
INSERT INTO event (
    continent,
    coordinate_precision,
    coordinate_uncertainty_in_meters,
    country, 
    country_code, 
    county, 
    data_generalizations,
    dataset_id,
    dataset_name,
    day,
    decimal_latitude, 
    decimal_longitude, 
    end_day_of_year,
    event_category, 
    event_conducted_by, 
    event_conducted_by_id,
    event_date, 
    event_effort, 
    event_id, 
    event_references, 
    event_remarks,
    event_time, 
    event_type, 
    field_notes,
    field_number,
    footprint_spatial_fit,
    footprint_srs,
    footprint_wkt,
    geodetic_datum, 
    georeferenced_by,
    georeferenced_by_id,
    georeferenced_date,
    georeference_protocol,
    georeference_protocol_id,
    georeference_remarks,
    georeference_sources,
    georeference_verification_status,
    habitat,
    higher_geography,
    higher_geography_id,
    information_withheld,
    island,
    island_group,
    locality, 
    location_id, 
    location_remarks, 
    maximum_depth_in_meters,
    maximum_distance_above_surface_in_meters,
    maximum_elevation_in_meters,
    minimum_depth_in_meters,
    minimum_distance_above_surface_in_meters,
    minimum_elevation_in_meters,
    month,
    municipality,
    parent_event_id,
    point_radius_spatial_fit,
    preferred_event_name,
    preferred_spatial_representation,
    start_day_of_year,
    state_province,
    verbatim_coordinates, 
    verbatim_coordinate_system,
    verbatim_depth,
    verbatim_elevation, 
    verbatim_event_date,
    verbatim_latitude,
    verbatim_locality,
    verbatim_longitude,
    verbatim_srs,
    vertical_datum,
    water_body,
    year 
)
(SELECT
  CONTINENT AS continent,
  NULLIF(COORDINATEPRECISION, '')::NUMERIC AS coordinate_precision,
  NULLIF(COORDINATEUNCERTAINTYINMETERS, '')::NUMERIC AS coordinate_uncertainty_in_meters,
  COUNTRY AS country,
  COUNTRYCODE AS country_code,
  COUNTY AS county,
  DATAGENERALIZATIONS AS data_generalizations,
  DATASETID AS dataset_id,
  DATASETNAME AS dataset_name,
  NULLIF(DAY, '')::INTEGER AS day,
  NULLIF(DECIMALLATITUDE, '')::NUMERIC AS decimal_latitude,
  NULLIF(DECIMALLONGITUDE, '')::NUMERIC AS decimal_longitude,
  NULLIF(ENDDAYOFYEAR, '')::INTEGER AS end_day_of_year,
  EVENTCATEGORY AS event_category,
  EVENTCONDUCTEDBY AS event_conducted_by,
  EVENTCONDUCTEDBYID AS event_conducted_by_id,
  EVENTDATE AS event_date,
  EVENTEFFORT AS event_effort,
  EVENTID as event_id,
  EVENTREFERENCES AS event_references,
  EVENTREMARKS AS event_remarks,
  EVENTTIME AS event_time,
  EVENTTYPE AS event_type,
  FIELDNOTES AS field_notes,
  FIELDNUMBER AS field_number,
  NULLIF(FOOTPRINTSPATIALFIT, '')::NUMERIC AS footprint_spatial_fit,
  FOOTPRINTSRS AS footprint_srs,
  FOOTPRINTWKT AS footprint_wkt,
  GEODETICDATUM AS geodetic_datum,
  GEOREFERENCEDBY AS georeferenced_by,
  GEOREFERENCEDBYID AS georeferenced_by_id,
  GEOREFERENCEDDATE AS georeferenced_date,
  GEOREFERENCEPROTOCOL AS georeference_protocol,
  GEOREFERENCEPROTOCOLID AS georeference_protocol_id,
  GEOREFERENCEREMARKS AS georeference_remarks,
  GEOREFERENCESOURCES AS georeference_sources,
  GEOREFERENCEVERIFICATIONSTATUS AS georeference_verification_status,
  HABITAT AS habitat,
  HIGHERGEOGRAPHY AS higher_geography,
  HIGHERGEOGRAPHYID AS higher_geography_id,
  INFORMATIONWITHHELD AS information_withheld,
  ISLAND AS island,
  ISLANDGROUP AS island_group,
  LOCALITY AS locality,
  LOCATIONID AS location_id,
  LOCATIONREMARKS AS location_remarks,
  NULLIF(MAXIMUMDEPTHINMETERS, '')::NUMERIC AS maximum_depth_in_meters,
  NULLIF(MAXIMUMDISTANCEABOVESURFACEINMETERS, '')::NUMERIC AS maximum_distance_above_surface_in_meters,
  NULLIF(MAXIMUMELEVATIONINMETERS, '')::NUMERIC AS maximum_elevation_in_meters,
  NULLIF(MINIMUMDEPTHINMETERS, '')::NUMERIC AS minimum_depth_in_meters,
  NULLIF(MINIMUMDISTANCEABOVESURFACEINMETERS, '')::NUMERIC AS minimum_distance_above_surface_in_meters,
  NULLIF(MINIMUMELEVATIONINMETERS, '')::NUMERIC AS minimum_elevation_in_meters,
  NULLIF(MONTH, '')::INTEGER AS month,
  MUNICIPALITY AS municipality,
  NULLIF(PARENTEVENTID, '') AS parent_event_id,
  NULLIF(POINTRADIUSSPATIALFIT, '')::NUMERIC AS point_radius_spatial_fit,
  PREFERREDEVENTNAME AS preferred_event_name,
  PREFERREDSPATIALREPRESENTATION AS preferred_spatial_representation,
  NULLIF(STARTDAYOFYEAR, '')::INTEGER AS start_day_of_year,
  STATEPROVINCE AS state_province,
  VERBATIMCOORDINATES AS verbatim_coordinates,
  VERBATIMCOORDINATESYSTEM AS verbatim_coordinate_system,
  VERBATIMDEPTH AS verbatim_depth,
  VERBATIMELEVATION AS verbatim_elevation,
  VERBATIMEVENTDATE AS verbatim_event_date,
  VERBATIMLATITUDE AS verbatim_latitude,
  VERBATIMLOCALITY AS verbatim_locality,
  VERBATIMLONGITUDE AS verbatim_longitude,
  VERBATIMSRS AS verbatim_srs,
  VERTICALDATUM AS vertical_datum,
  WATERBODY AS waterbody,
  NULLIF(YEAR, '')::INTEGER AS year
FROM input_event
);
-- n = 290

-- Fill the material table.
INSERT INTO material (
    associated_sequences,
    catalog_number,
    collected_by,
    collected_by_id,
    collection_code,
    collection_id,
    data_generalizations,
    date_identified,
    derivation_event_id,
    derivation_type,
    derived_from_material_entity_id,
    digital_specimen_id,
    disposition,
    event_id,
    evidence_for_occurrence_id,
    higher_classification_name,
    higher_classification_rank,
    identification_references,
    identification_remarks,
    identification_verification_status,
    identified_by,
    identified_by_id,
    information_withheld,
    institution_code,
    institution_id,
    is_part_of_material_entity_id,
    material_category,
    material_entity_id,
    material_entity_remarks,
    material_entity_type,
    material_references,
    object_quantity,
    object_quantity_type,
    other_catalog_numbers,
    owner_institution_code,
    owner_institution_id,
    preparations,
    record_number,
    scientific_name,
    taxon_formula,
    taxon_id,
    taxon_rank,
    taxon_remarks,
    type_designation_type,
    type_status,
    typified_name,
    verbatim_identification,
    verbatim_label
)
(
SELECT 
  ASSOCIATEDSEQUENCES AS associate_sequences,
  CATALOGNUMBER AS catalog_number,
  COLLECTEDBY AS collected_by,
  COLLECTEDBYID AS collected_by_id,
  COLLECTIONCODE AS collection_code,
  COLLECTIONID AS collection_id,
  DATAGENERALIZATIONS AS data_generalizations,
  DATEIDENTIFIED AS date_identified,
  DERIVATIONEVENTID AS derivation_event_id,
  DERIVATIONTYPE AS derivation_type,
  DERIVEDFROMMATERIALENTITYID AS derived_from_material_entity_id,
  DIGITALSPECIMENID AS digital_specimen_id,
  DISPOSITION AS disposition,
  EVENTID AS event_id,
  EVIDENCEFOROCCURRENCEID AS evidence_for_occurrence_id,
  HIGHERCLASSIFICATIONNAME AS higher_classification_name,
  HIGHERCLASSIFICATIONRANK AS higher_classification_rank,
  IDENTIFICATIONREFERENCES AS identification_references,
  IDENTIFICATIONREMARKS AS identification_remarks,
  IDENTIFICATIONVERIFICATIONSTATUS AS identification_verification_status,
  IDENTIFIEDBY AS identified_by,
  IDENTIFIEDBYID AS identified_by_id,
  INFORMATIONWITHHELD AS information_withheld,
  INSTITUTIONCODE AS institution_code,
  INSTITUTIONID AS institution_id,
  ISPARTOFMATERIALENTITYID AS is_part_of_material_entity_id,
  'preserved' AS material_category,
  MATERIALENTITYID AS material_entity_id,
  MATERIALENTITYREMARKS AS material_entity_remarks,
  MATERIALENTITYTYPE AS material_entity_type,
  MATERIALREFERENCES AS material_references,
  OBJECTQUANTITY AS object_quantity,
  OBJECTQUANTITYTYPE AS object_quantity_type,
  OTHERCATALOGNUMBERS AS other_catalog_numbers,
  OWNERINSTITUTIONCODE AS owner_institution_code,
  OWNERINSTITUTIONID AS owner_institution_id,
  PREPARATIONS AS preparations,
  RECORDNUMBER AS record_number,
  SCIENTIFICNAME AS scientific_name,
  TAXONFORMULA AS taxon_formula,
  TAXONID AS taxon_id,
  TAXONRANK AS taxon_rank,
  TAXONREMARKS AS taxon_remarks,
  TYPEDESIGNATIONTYPE AS type_designation_type,
  TYPESTATUS AS type_status,
  TYPIFIEDNAME AS typified_name,
  VERBATIMIDENTIFICATION AS verbatim_identification,
  VERBATIMLABEL AS verbatim_label
FROM input_material
);
-- n = 300

-- Fill the occurrence table.
INSERT INTO occurrence (
    behavior,
    caste,
    data_generalizations,
    date_identified,
    degree_of_establishment,
    establishment_means,
    event_id,
    higher_classification_name,
    higher_classification_rank,
    identification_references,
    identification_remarks,
    identification_verification_status,
    identified_by,
    identified_by_id,
    information_withheld,
    life_stage,
    occurrence_id,
    occurrence_references,
    occurrence_remarks,
    occurrence_status,
    organism_id,
    organism_name,
    organism_quantity,
    organism_quantity_type,
    organism_remarks,
    organism_scope,
    pathway,
    recorded_by,
    recorded_by_id,
    reproductive_condition,
    scientific_name,
    sex,
    survey_target_id,
    taxon_formula,
    taxon_id,
    taxon_rank,
    taxon_remarks,
    verbatim_identification,
    vitality
)
(SELECT
  BEHAVIOR AS behavior,
  CASTE AS caste,
  DATAGENERALIZATIONS AS data_generalizations,
  DATEIDENTIFIED AS date_identified,
  DEGREEOFESTABLISHMENT AS degree_of_establishment,
  ESTABLISHMENTMEANS AS establishment_means,
  EVENTID AS event_id,
  HIGHERCLASSIFICATIONNAME AS higher_classification_name,
  HIGHERCLASSIFICATIONRANK AS higher_classification_rank,
  IDENTIFICATIONREFERENCES AS identification_references,
  IDENTIFICATIONREMARKS AS identification_remarks,
  IDENTIFICATIONVERIFICATIONSTATUS AS identification_verification_status,
  IDENTIFIEDBY AS identified_by,
  IDENTIFIEDBYID AS identified_by_id,
  INFORMATIONWITHHELD AS information_withheld,
  LIFESTAGE AS life_stage,
  OCCURRENCEID AS occurrence_id,
  OCCURRENCEREFERENCES AS occurrence_references,
  OCCURRENCEREMARKS AS occurrence_remarks,
  COALESCE(NULLIF(OCCURRENCESTATUS, ''), 'detected')::OCCURRENCE_STATUS AS occurrence_status,
  ORGANISMID AS organism_id,
  ORGANISMNAME AS organism_name,
  ORGANISMQUANTITY AS organism_quantity,
  ORGANISMQUANTITYTYPE AS organism_quantity_type,
  ORGANISMREMARKS AS organism_remarks,
  ORGANISMSCOPE AS organism_scope,
  PATHWAY AS pathway,
  RECORDEDBY AS recorded_by,
  RECORDEDBYID AS recorded_by_id,
  REPRODUCTIVECONDITION AS reproductive_condition,
  SCIENTIFICNAME AS scientific_name,
  SEX AS sex,
  SURVEYTARGETID AS survey_target_id,
  TAXONFORMULA AS taxon_formula,
  TAXONID AS taxon_id,
  TAXONRANK AS taxon_rank,
  TAXONREMARKS AS taxon_remarks,
  VERBATIMIDENTIFICATION AS verbatim_identification,
  VITALITY AS vitality
FROM input_occurrence
);
-- n = 

-- Fill the agent table.
INSERT INTO agent (
    agent_id,
    agent_type,
    agent_type_iri,
    agent_type_vocabulary,
    preferred_agent_name
)
(SELECT
    AGENTID AS agent_id,
    AGENTTYPE AS agent_type,
    AGENTTYPEIRI AS agent_type_iri,
    AGENTTYPEVOCABULARY AS agent_type_vocabulary,
    PREFERREDAGENTNAME AS preferred_agent_name
FROM input_agent
);
-- n = 153

-- Fill the event_agent_role table.
INSERT INTO event_agent_role (
    agent_id,
    agent_role,
    agent_role_date,
    agent_role_iri,
    agent_role_order,
    agent_role_vocabulary,
    event_id
)
(SELECT
  AGENTID AS agent_id,
  AGENTROLE AS agent_role,
  AGENTROLEDATE AS agent_role_date,
  AGENTROLEIRI AS agent_role_iri,
  COALESCE(NULLIF(AGENTROLEORDER, ''), '1')::INTEGER AS agent_role_order,
  AGENTROLEVOCABULARY AS agent_role_vocabulary,
  EVENTID AS event_id
FROM input_event_agent_role
);
-- n = 222

-- Fill the identification table.
INSERT INTO identification (
    based_on_material_entity_id,
    based_on_media_id,
    based_on_nucleotide_analysis_id,
    based_on_nucleotide_sequence_id,
    based_on_occurrence_id,
    date_identified,
    higher_classification_name,
    higher_classification_rank,
    identification_id,
    identification_references,
    identification_remarks,
    identification_verification_status,
    identified_by,
    identified_by_id,
    is_accepted_identification,
    scientific_name,
    taxon_assignment_method,
    taxon_formula,
    taxon_id,
    taxon_rank,
    taxon_remarks,
    type_designation_type,
    type_status,
    verbatim_identification
)
(SELECT
  BASEDONMATERIALENTITYID AS based_on_material_entity_id,
  BASEDONMEDIAID AS based_on_media_id,
  BASEDONNUCLEOTIDEANALYSISID AS based_on_nucleotide_analysis_id,
  BASEDONNUCLEOTIDESEQUENCEID AS based_on_nucleotide_sequence_id,
  BASEDONOCCURRENCEID AS based_on_occurrence_id,
  DATEIDENTIFIED AS date_identified,
  HIGHERCLASSIFICATIONNAME AS higher_classification_name,
  HIGHERCLASSIFICATIONRANK AS higher_classification_rank,
  IDENTIFICATIONID AS identification_id,
  IDENTIFICATIONREFERENCES AS identification_references,
  IDENTIFICATIONREMARKS AS identification_remarks,
  IDENTIFICATIONVERIFICATIONSTATUS AS identification_verification_status,
  IDENTIFIEDBY AS identified_by,
  IDENTIFIEDBYID AS identified_by_id,
  ISACCEPTEDIDENTIFICATION AS accepted_identification_id,
  SCIENTIFICNAME AS scientific_name,
  TAXONASSIGNMENTMETHOD AS taxon_assignment_method,
  TAXONFORMULA AS taxon_formula,
  TAXONID AS taxon_id,
  TAXONRANK AS taxon_rank,
  TAXONREMARKS AS taxon_remarks,
  TYPEDESIGNATIONTYPE AS type_designation_type,
  TYPESTATUS AS type_status,
  VERBATIMIDENTIFICATION AS verbatim_identification
FROM input_identification
);
-- n = 300

-- Fill the identification_taxon table.
INSERT INTO identification_taxon (
    higher_classification_name,
    higher_classification_rank,
    identification_id,
    scientific_name,
    taxon_id,
    taxon_sort_order,
    taxon_rank,
    taxon_remarks
)
(SELECT
  HIGHERCLASSIFICATIONNAME AS higher_classification_name,
  HIGHERCLASSIFICATIONRANK AS higher_classification_rank,
  IDENTIFICATIONID AS identification_id,
  SCIENTIFICNAME AS scientific_name,
  TAXONID AS taxon_id,
  COALESCE(NULLIF(TAXONORDER, '')::INTEGER, '1') AS taxon_sort_order,
  TAXONRANK AS taxon_rank,
  TAXONREMARKS AS taxon_remarks
FROM input_identification_taxon
);
-- n = 271

-- Fill the material_assertion table.
--INSERT INTO material_assertion (
--)
--(SELECT
--FROM input_material_assertion
--);
-- n = 

-- Fill the material_identifier table.

INSERT INTO material_identifier (
    identifier,
    identifier_language,
    identifier_type,
    identifier_type_iri,
    identifier_type_vocabulary,
    material_entity_id
)
(SELECT
  IDENTIFIER AS identifier,
  IDENTIFIERLANGUAGE AS identifier_language,
  IDENTIFIERTYPE AS identifier_type,
  IDENTIFIERTYPEIRI AS identifier_type_iri,
  IDENTIFIERTYPEVOCABULARY AS identifier_type_vocabulary,
  MATERIALENTITYID AS material_entity_id
FROM input_material_identifier
);
-- n = 300

-- Fill the media table.
INSERT INTO media (
    access_uri,
    attribution_link_url,
    attribution_logo_url,
    available,
    caption,
    capture_device,
    collection_code,
    collection_id,
    commenter,
    commenter_literal,
    comments,
    create_date,
    creator,
    creator_iri,
    credit,
    derived_from,
    description,
    feedback_url,
    format,
    format_iri,
    funding_attribution,
    funding_attribution_id,
    further_information_url,
    hash_function,
    hash_value,
    has_service_access_point,
    language,
    language_iri,
    license_logo_url,
    licensing_exception,
    media_id,
    media_type,
    metadata_creator,
    metadata_creator_literal,
    metadata_date,
    metadata_language,
    metadata_language_literal,
    metadata_provider,
    metadata_provider_literal,
    modified,
    owner,
    pixel_x_dimension,
    pixel_y_dimension,
    provider,
    provider_literal,
    resource_creation_technique,
    reviewer,
    reviewer_comments,
    reviewer_literal,
    rights,
    rights_iri,
    service_expectation,
    source,
    source_iri,
    subtype,
    subtype_literal,
    tag,
    time_of_day,
    title,
    usage_terms,
    variant,
    variant_description,
    variant_literal,
    web_statement
)
(SELECT
  ACCESSURI AS access_uri,
  ATTRIBUTIONLINKURL AS attribution_link_url,
  ATTRIBUTIONLOGOURL AS attribution_logo_url,
  AVAILABLE AS available,
  CAPTION AS caption,
  CAPTUREDEVICE AS capture_device,
  COLLECTIONCODE AS collection_code,
  COLLECTIONID AS collection_id,
  COMMENTER AS commenter,
  COMMENTERLITERAL AS commenter_literal,
  COMMENTS AS comments,
  CREATEDATE AS create_date,
  CREATOR AS creator,
  CREATORIRI AS creator_iri,
  CREDIT AS credit,
  DERIVEDFROM AS derived_from,
  DESCRIPTION AS description,
  FEEDBACKURL AS feedback_url,
  FORMAT AS format,
  FORMATIRI AS format_iri,
  FUNDINGATTRIBUTION AS funding_attribution,
  FUNDINGATTRIBUTIONID AS funding_attribution_id,
  FURTHERINFORMATIONURL AS further_information_url,
  HASHFUNCTION AS hash_function,
  HASHVALUE AS hash_value,
  HASSERVICEACCESSPOINT AS has_service_access_point,
  LANGUAGE AS language,
  LANGUAGEIRI AS language_iri,
  LICENSELOGOURL AS license_logo_url,
  LICENSINGEXCEPTION AS licensing_exception,
  MEDIAID AS media_id,
  MEDIATYPE AS media_type,
  METADATACREATOR AS metadata_creator,
  METADATACREATORLITERAL AS metadata_creator_literal,
  METADATADATE AS metadata_date,
  METADATALANGUAGE AS metadata_language,
  METADATALANGUAGELITERAL AS metadata_language_literal,
  METADATAPROVIDER AS metadata_provider,
  METADATAPROVIDERLITERAL AS metadata_provider_literal,
  MODIFIED AS modified,
  OWNER AS owner,
  NULLIF(PIXELXDIMENSION, 'null')::INTEGER AS pixel_x_dimension,
  NULLIF(PIXELYDIMENSION, 'null')::INTEGER AS pixel_y_dimension,
  PROVIDER AS provider,
  PROVIDERLITERAL AS provider_literal,
  RESOURCECREATIONTECHNIQUE AS resource_creation_technique,
  REVIEWER AS reviewer,
  REVIEWERCOMMENTS AS reviewer_comments,
  REVIEWERLITERAL AS reviewer_literal,
  RIGHTS AS rights,
  RIGHTSIRI AS rights_iri,
  SERVICEEXPECTATION AS service_expectation,
  SOURCE AS source,
  SOURCEIRI AS source_iri,
  SUBTYPE AS subtype,
  SUBTYPELITERAL AS subtype_literal,
  TAG AS tag,
  TIMEOFDAY AS time_of_day,
  TITLE AS title,
  USAGETERMS AS usage_terms,
  VARIANT AS variant,
  VARIANTDESCRIPTION AS variant_description,
  VARIANTLITERAL AS variant_literal,
  WEBSTATEMENT AS web_statement
FROM input_media
);
-- n = 165

-- Fill the material_media table.
INSERT INTO material_media (
    material_entity_id,
    media_id,
    media_subject_category,
    media_subject_category_iri,
    media_subject_category_vocabulary
)
(SELECT
  MATERIALENTITYID AS material_entity_id,
  MEDIAID AS media_id,
  MEDIASUBJECTCATEGORY AS media_subject_category,
  MEDIASUBJECTCATEGORYIRI AS media_subject_category_iri,
  MEDIASUBJECTCATEGORYVOCABULARY AS media_subject_category_vocabulary
FROM input_material_media
);
-- n = 165

-- Not mappable with the original data provided.
-- Fill the relationship table.
-- INSERT INTO relationship (
--   related_resource_id,
--   related_resource_type,
--   related_resource_type_iri,
--   related_resource_type_vocabulary,
--   relationship_according_to,
--   relationship_according_to_id,
--   relationship_effective_date,
--   relationship_id,
--   relationship_order,
--   relationship_remarks,
--   relationship_type,
--   relationship_type_iri,
--   relationship_type_vocabulary,
--   subject_resource_id,
--   subject_resource_type,
--   subject_resource_type_iri,
--   subject_resource_type_vocabulary
-- )
-- (SELECT
--   RELATEDRESOURCEID AS related_resource_id,
--   RELATEDRESOURCETYPE AS related_resource_type,
--   RELATEDRESOURCETYPEIRI AS related_resource_type_iri,
--   RELATEDRESOURCETYPEVOCABULARY AS related_resource_type_vocabulary,
--   RELATIONSHIPACCORDINGTO AS relationship_according_to,
--   RELATIONSHIPACCORDINGTOID AS relationship_relationship_according_to_id,
--   RELATIONSHIPEFFECTIVEDATE AS relationship_effective_date,
--   RELATIONSHIPID AS relationship_id,
--   RELATIONSHIPORDER AS relationship_order,
--   RELATIONSHIPREMARKS AS relationship_remarks,
--   RELATIONSHIPTYPE AS relationship_type,
--   RELATIONSHIPTYPEIRI AS relationship_type_iri,
--   RELATIONSHIPTYPEVOCABULARY AS relationship_type_vocabulary,
--   SUBJECTRESOURCEID AS subject_resource_id,
--   SUBJECTRESOURCETYPE AS subject_resource_type,
--   SUBJECTRESOURCETYPEIRI AS subject_resource_type_iri,
--   SUBJECTRESOURCETYPEVOCABULARY AS subject_resource_type_vocabulary
-- FROM input_relationship
-- );
-- -- n = 
