---
title: "Transform Movebank data to a Darwin Core Data Package"
author: "Sanne Govaert"
date: "`r Sys.Date()`"
output: html_document
---

Transforms a Movebank dataset (formatted as a [Frictionless Data Package](https://specs.frictionlessdata.io/data-package/)) to a [Darwin Core Data Package](https://gbif.github.io/dwc-dp/) as part of the public review.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(movepub)
library(dplyr)
```

```{r dataset}
package <- o_assen
```

```{r}
ref <- movepub::read_resource(package, "reference-data") %>% 
  dplyr::mutate(
    `tag-model` = NA_character_,
    `animal-reproductive-condition` = NA_character_
    )

# Lookup AphiaIDs for taxa
names <- dplyr::pull(dplyr::distinct(ref, .data$`animal-taxon`))
taxa <- get_aphia_id(names)


gps <- movepub::read_resource(package, "gps") %>% 
  dplyr::mutate(
    comments = NA_character_,
    `height-above-ellipsoid` = NA_character_
    ) %>% 
  # Exclude outliers & (rare) empty coordinates
  dplyr::filter(.data$visible & !is.na(.data$`location-lat`)) %>%
  dplyr::mutate(
    time_per_hour = strftime(.data$timestamp, "%y-%m-%d %H %Z", tz = "UTC")
  ) %>%
  # Group by animal+tag+date+hour combination
  dplyr::group_by(
    .data$`individual-local-identifier`,
    .data$`tag-local-identifier`,
    .data$time_per_hour
  ) %>%
  dplyr::arrange(.data$timestamp) %>%
  dplyr::mutate(subsample_count = dplyr::n()) %>%
  # Take first record/timestamp within group
  dplyr::filter(dplyr::row_number() == 1) %>%
  dplyr::ungroup() %>%
  # Join with reference data
  dplyr::left_join(
    ref,
    by = dplyr::join_by(
      "individual-local-identifier" == "animal-id",
      "tag-local-identifier" == "tag-id"
    )
  ) %>%
  # Exclude (rare) records outside a deployment
  dplyr::filter(!is.na(.data$`animal-taxon`)) %>%
  dplyr::left_join(taxa, by = dplyr::join_by("animal-taxon" == "name")) 
```

```{r ref_event}
ref_event <-
  ref %>%
  dplyr::mutate(
    .keep = "none",
    eventID = paste(.data$`animal-id`, .data$`tag-id`, "start", sep = "_"),
    parentEventID = paste(.data$`animal-id`, .data$`tag-id`, sep = "_"),
    preferredEventName = NA_character_,
    eventCategory = NA_character_,
    eventType = "tag attachment",
    datasetName = NA_character_,
    datasetID = NA_character_,
    fieldNumber = NA_character_,
    eventConductedBy = NA_character_,
    eventConductedByID = NA_character_,
    eventDate = format(.data$`deploy-on-date`, format = "%Y-%m-%dT%H:%M:%SZ"),
    eventTime = NA_character_,
    startDayOfYear = NA_integer_,
    endDayOfYear = NA_integer_,
    year = NA_integer_,
    month = NA_integer_,
    day = NA_integer_,
    verbatimEventDate = NA_character_,
    verbatimLocality = NA_character_,
    verbatimElevation = NA_character_,
    verbatimDepth = NA_character_,
    verbatimCoordinates = NA_character_,
    verbatimLatitude = NA_character_,
    verbatimLongitude = NA_character_,
    verbatimCoordinateSystem = NA_character_,
    verbatimSRS = NA_character_,
    georeferenceVerificationStatus = NA_character_,
    habitat = NA_character_,
    eventEffort = NA_character_,
    fieldNotes = NA_character_,
    eventReferences = NA_character_,
    eventRemarks = paste0(
      dplyr::if_else(
        is.na(.data$`tag-manufacturer-name`),
        "tag ",
        dplyr::if_else(
          is.na(.data$`tag-model`),
          paste(.data$`tag-manufacturer-name`, "tag "),
          paste(.data$`tag-manufacturer-name`, .data$`tag-model`, "tag ")
        )
      ),
      dplyr::if_else(
        !is.na(.data$`attachment-type`),
        paste("attached by", .data$`attachment-type`, "to "),
        "attached to "
      ),
      dplyr::recode(
        .data$`manipulation-type`,
        "none" = "free-ranging animal",
        "confined" = "confined animal",
        "recolated" = "relocated animal",
        "manipulated other" = "manipulated animal",
        .default = "likely free-ranging animal",
        .missing = "likely free-ranging animal"
      ),
      dplyr::if_else(
        !is.na(.data$`deployment-comments`),
        paste0(" | ", .data$`deployment-comments`),
        ""
      )
    ),
    locationID = NA_character_,
    higherGeographyID = NA_character_,
    higherGeography = NA_character_,
    continent = NA_character_,
    waterBody = NA_character_,
    islandGroup = NA_character_,
    island = NA_character_,
    country = NA_character_,
    countryCode = NA_character_,
    stateProvince = NA_character_,
    county = NA_character_,
    municipality = NA_character_,
    locality = NA_character_,
    minimumElevationInMeters = NA_real_,
    maximumElevationInMeters = NA_real_,
    verticalDatum = NA_character_,
    minimumDepthInMeters = NA_real_,
    maximumDepthInMeters = NA_real_,
    minimumDistanceAboveSurfaceInMeters = NA_real_,
    maximumDistanceAboveSurfaceInMeters = NA_real_,
    locationRemarks = NA_character_,
    decimalLatitude = as.numeric(.data$`deploy-on-latitude`),
    decimalLongitude = as.numeric(.data$`deploy-on-longitude`),
    geodeticDatum = dplyr::if_else(
      !is.na(.data$`deploy-on-latitude`),
      "EPSG:4326",
      NA_character_
    ),
    coordinateUncertaintyInMeters = NA_real_,
    coordinatePrecision = NA_real_,
    pointRadiusSpatialFit = NA_real_,
    footprintWKT = NA_character_,
    footprintSRS = NA_character_,
    footprintSpatialFit = NA_real_,
    georeferencedBy = NA_character_,
    georeferencedByID = NA_character_,
    georeferencedDate = NA_character_,
    georeferenceProtocol = NA_character_,
    georeferenceProtocolID = NA_character_,
    georeferenceSources = NA_character_,
    georeferenceRemarks = NA_character_,
    informationWithheld = NA_character_,
    dataGeneralizations = NA_character_,
    preferredSpatialRepresentation = NA_character_,
    projectID = NA_character_,
    projectTitle = NA_character_,
    fundingAttribution = NA_character_,
    fundingAttributionID = NA_character_,
    feedbackURL = NA_character_
  )

```

```{r gps_event}
gps_event <-
  gps %>%
  dplyr::mutate(
    .keep = "none",
    eventID = as.character(.data$`event-id`),
    parentEventID = paste(
      .data$`individual-local-identifier`,
      .data$`tag-local-identifier`,
      sep = "_"
    ),
    preferredEventName = NA_character_,
    eventCategory = NA_character_,
    eventType = "gps",
    datasetName = NA_character_,
    datasetID = NA_character_,
    fieldNumber = NA_character_,
    eventConductedBy = NA_character_,
    eventConductedByID = NA_character_,
    eventDate = format(.data$timestamp, format = "%Y-%m-%dT%H:%M:%SZ"),
    eventTime = NA_character_,
    startDayOfYear = NA_integer_,
    endDayOfYear = NA_integer_,
    year = NA_integer_,
    month = NA_integer_,
    day = NA_integer_,
    verbatimEventDate = NA_character_,
    verbatimLocality = NA_character_,
    verbatimElevation = NA_character_,
    verbatimDepth = NA_character_,
    verbatimCoordinates = NA_character_,
    verbatimLatitude = NA_character_,
    verbatimLongitude = NA_character_,
    verbatimCoordinateSystem = NA_character_,
    verbatimSRS = NA_character_,
    georeferenceVerificationStatus = NA_character_,
    habitat = NA_character_,
    eventEffort = NA_character_,
    fieldNotes = NA_character_,
    eventReferences = NA_character_,
    eventRemarks = dplyr::coalesce(.data$`comments`, ""),
    locationID = NA_character_,
    higherGeographyID = NA_character_,
    higherGeography = NA_character_,
    continent = NA_character_,
    waterBody = NA_character_,
    islandGroup = NA_character_,
    island = NA_character_,
    country = NA_character_,
    countryCode = NA_character_,
    stateProvince = NA_character_,
    county = NA_character_,
    municipality = NA_character_,
    locality = NA_character_,
    minimumElevationInMeters = dplyr::coalesce(
      .data$`height-above-msl`,
      as.numeric(.data$`height-above-ellipsoid`),
      NA_real_
    ),
    maximumElevationInMeters = dplyr::coalesce(
      .data$`height-above-msl`,
      as.numeric(.data$`height-above-ellipsoid`),
      NA_real_
    ),
    verticalDatum = NA_character_,
    minimumDepthInMeters = NA_real_,
    maximumDepthInMeters = NA_real_,
    minimumDistanceAboveSurfaceInMeters = NA_real_,
    maximumDistanceAboveSurfaceInMeters = NA_real_,
    locationRemarks = dplyr::case_when(
      !is.na(.data$`height-above-msl`) ~
        "elevations are altitude above mean sea level",
      !is.na(.data$`height-above-ellipsoid`) ~
        "elevations are altitude above ellipsoid"
    ),
    decimalLatitude = as.numeric(.data$`location-lat`),
    decimalLongitude = as.numeric(.data$`location-long`),
    geodeticDatum = "EPSG:4326",
    coordinateUncertaintyInMeters =
      as.numeric(.data$`location-error-numerical`),
    coordinatePrecision = NA_real_,
    pointRadiusSpatialFit = NA_real_,
    footprintWKT = NA_character_,
    footprintSRS = NA_character_,
    footprintSpatialFit = NA_real_,
    georeferencedBy = NA_character_,
    georeferencedByID = NA_character_,
    georeferencedDate = NA_character_,
    georeferenceProtocol = NA_character_,
    georeferenceProtocolID = NA_character_,
    georeferenceSources = NA_character_,
    georeferenceRemarks = NA_character_,
    informationWithheld = NA_character_,
    dataGeneralizations = paste(
      "subsampled by hour: first of", .data$subsample_count, "record(s)"
    ),
    preferredSpatialRepresentation = NA_character_,
    projectID = NA_character_,
    projectTitle = NA_character_,
    fundingAttribution = NA_character_,
    fundingAttributionID = NA_character_,
    feedbackURL = NA_character_
  )
```

```{r event}
not_all_na <- function(x) any(!is.na(x))
event <-
  ref_event %>%
  dplyr::bind_rows(gps_event) %>%
  dplyr::arrange(eventID) %>% 
  dplyr::select(where(not_all_na)) %>% 
  distinct() %>% 
  dplyr::mutate(
      # DATASET-LEVEL
      datasetID = package$id,
      datasetName = package$title,
      .before = "eventDate"
    ) %>% 
    dplyr::arrange(.data$parentEventID, .data$eventDate)
```


```{r ref_occurrence}
ref_occurrence <-
  ref %>% 
  dplyr::filter(!is.na(.data$`deploy-on-date`)) %>% 
  dplyr::left_join(taxa, by = dplyr::join_by("animal-taxon" == "name")) %>% 
  dplyr::mutate(
    .keep = "none",
    occurrenceID = paste(
        .data$`animal-id`, .data$`tag-id`, "start", sep = "_" # Same as eventID
      ),
    eventID = paste(.data$`animal-id`, .data$`tag-id`, "start", sep = "_"),
    surveyTargetID = NA_character_,
    recordedBy = NA_character_,
    recordedByID = NA_character_,
    organismQuantity = NA_character_,
    organismQuantityType = NA_character_,
    sex = dplyr::recode(
        .data$`animal-sex`,
        "m" = "male",
        "f" = "female",
        "u" = "unknown"
      ),
    lifeStage = .data$`animal-life-stage`,
    reproductiveCondition = .data$`animal-reproductive-condition`,
    caste = NA_character_,
    behavior = NA_character_,
    vitality = NA_character_,
    establishmentMeans = NA_character_,
    degreeOfEstablishment = NA_character_,
    pathway = NA_character_,
    substrate = NA_character_,
    occurrenceStatus = "present",
    occurrenceReferences = NA_character_,
    informationWithheld = NA_character_,
    dataGeneralizations = NA_character_,
    occurrenceRemarks = NA_character_,
    organismID = .data$`animal-id`,
    organismScope = NA_character_,
    organismName = .data$`animal-nickname`,
    causeOfDeath = NA_character_,
    organismRemarks = NA_character_,
    verbatimIdentification = NA_character_,
    taxonFormula = NA_character_,
    identifiedBy = NA_character_,
    identifiedByID = NA_character_,
    dateIdentified = NA_character_,
    identificationReferences = NA_character_,
    identificationVerificationStatus = NA_character_,
    identificationRemarks = NA_character_,
    taxonID = .data$aphia_lsid,
    higherClassificationName = "Animalia",
    higherClassificationRank = "kingdom",
    scientificName = .data$`animal-taxon`,
    taxonRank = "species",
    taxonRemarks = NA_character_,
    feedbackURL = NA_character_
  )
```

```{r}
gps_occurrence <-
  gps %>% 
  dplyr::mutate(
    .keep = "none",
    occurrenceID = as.character(.data$`event-id`),
    eventID = as.character(.data$`event-id`),
    surveyTargetID = NA_character_,
    recordedBy = NA_character_,
    recordedByID = NA_character_,
    organismQuantity = NA_character_,
    organismQuantityType = NA_character_,
    sex = dplyr::recode(
        .data$`animal-sex`,
        "m" = "male",
        "f" = "female",
        "u" = "unknown"
      ),
    lifeStage = NA_character_,
    reproductiveCondition = NA_character_,
    caste = NA_character_,
    behavior = NA_character_,
    vitality = NA_character_,
    establishmentMeans = NA_character_,
    degreeOfEstablishment = NA_character_,
    pathway = NA_character_,
    substrate = NA_character_,
    occurrenceStatus = "present",
    occurrenceReferences = NA_character_,
    informationWithheld = NA_character_,
    dataGeneralizations = NA_character_,
    occurrenceRemarks = NA_character_,
    organismID = .data$`individual-local-identifier`,
    organismScope = NA_character_,
    organismName = .data$`animal-nickname`,
    causeOfDeath = NA_character_,
    organismRemarks = NA_character_,
    verbatimIdentification = NA_character_,
    taxonFormula = NA_character_,
    identifiedBy = NA_character_,
    identifiedByID = NA_character_,
    dateIdentified = NA_character_,
    identificationReferences = NA_character_,
    identificationVerificationStatus = NA_character_,
    identificationRemarks = NA_character_,
    taxonID = .data$aphia_lsid,
    higherClassificationName = "Animalia",
    higherClassificationRank = "kingdom",
    scientificName = .data$`animal-taxon`,
    taxonRank = "species",
    taxonRemarks = NA_character_,
    feedbackURL = NA_character_
  )
```


```{r occurrence}
not_all_na <- function(x) any(!is.na(x))
occurrence <-
  ref_occurrence %>%
  dplyr::bind_rows(gps_occurrence) %>%
  dplyr::arrange(eventID) %>% 
  dplyr::select(where(not_all_na))
```

```{r occurrenceAssertion}
sex <-
  ref_occurrence %>%
  dplyr::mutate(
    .keep = "none",
    occurrenceID = .data$occurrenceID,
    assertionID = NA_character_, # Required
    assertionType = "sex",
    assertionTypeIRI =
      "http://vocab.nerc.ac.uk/collection/P01/current/ENTSEX01/",
    assertionValue = .data$sex, # Value as is
    assertionValueIRI = dplyr::recode(
      .data$sex,
      "female" = "http://vocab.nerc.ac.uk/collection/S10/current/S102/",
      "male" = "https://vocab.nerc.ac.uk/collection/S10/current/S103/",
      "unknown" = "https://vocab.nerc.ac.uk/collection/S10/current/S105/", # indeterminate
      .default = NA_character_, # Don't map other values
      .missing = "https://vocab.nerc.ac.uk/collection/S10/current/S104/" # not specified
    )
  )

lifestage <-
  ref_occurrence %>%
  dplyr::mutate(
    .keep = "none",
    occurrenceID = .data$occurrenceID,
    assertionType = "life stage",
    assertionTypeIRI =
      "http://vocab.nerc.ac.uk/collection/P01/current/LSTAGE01/",
    assertionValue = .data$lifeStage, # Value as is
    assertionValueIRI = dplyr::recode(
      .data$lifeStage,
      "adult" = "http://vocab.nerc.ac.uk/collection/S11/current/S1116/",
      "subadult" = "https://vocab.nerc.ac.uk/collection/S11/current/S120/", # sub-adult
      "juvenile" = "https://vocab.nerc.ac.uk/collection/S11/current/S1127/",
      "unknown" = "http://vocab.nerc.ac.uk/collection/S11/current/S1152/", # indeterminate
      .default = NA_character_, # Don't map other values
      .missing = "http://vocab.nerc.ac.uk/collection/S11/current/S1131/" # not specified
    )
  )

occurrenceAssertion <-
  dplyr::bind_rows(sex, lifestage) %>%
  dplyr::arrange(.data$occurrenceID)
```


```{r identification}
identification
```

```{r provenance}
provenance
```

```{r}
# Compare with DwcA
dwc <- movepub::write_dwc(package, directory = "my_directory")
unlink("my_directory", recursive = TRUE)

nrow(dwc$occurrence) == nrow(occurrence)
```




